// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqgphylharoznvxvfcwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxZ3BoeWxoYXJvem52eHZmY3d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMzk0NTgsImV4cCI6MjA3MDkxNTQ1OH0.590xR8IJmeUDwofQeZAkcezJHykAuNPnlvqnAU8N-H8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});